# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u0nNr1tLjdatBcnyRlds6ASbc4ql255P
"""
import requests

def download_file_from_google_drive(id, destination):
    def get_confirm_token(response):
        for key, value in response.cookies.items():
            if key.startswith('download_warning'):
                return value

        return None

    def save_response_content(response, destination):
        CHUNK_SIZE = 32768

        with open(destination, "wb") as f:
            print("WRITING")
            for chunk in response.iter_content(CHUNK_SIZE):
                print("ANOTHER ONE")
                if chunk: # filter out keep-alive new chunks
                    f.write(chunk)
            print("YOU DONE NOW")

    URL = "https://docs.google.com/uc?export=download"

    session = requests.Session()

    response = session.get(URL, params = { 'id' : id }, stream = True)
    token = get_confirm_token(response)

    if token:
        params = { 'id' : id, 'confirm' : token }
        response = session.get(URL, params = params, stream = True)

    save_response_content(response, destination)

# TAKE ID FROM SHAREABLE LINK
file_id = '0BxRIhBA0x8lHNDJFVjJEQnZtcmc'
# DESTINATION FILE ON YOUR DISK
destination = "SRGAN_pre-trained.tars"
download_file_from_google_drive(file_id, destination)
